export const EP = {
  authMe:            '/auth/me',
  authLogin:         '/auth/login',
  authLogout:        '/auth/logout',
  sessionsCurrent:   '/sessions/current',
  sessions:          '/sessions',
  session:           (id: number) => `/sessions/${id}`,
  sessionReport:     (id: number) => `/sessions/${id}/report`,
  menus:             '/menus',
  menu:              (id: number) => `/menus/${id}`,
  menuSort:          '/menus/sort',
  categories:        '/categories',
  category:          (id: number) => `/categories/${id}`,
  subcategories:     '/subcategories',
  subcategory:       (id: number) => `/subcategories/${id}`,
  seats:             '/seats',
  seat:              (id: number) => `/seats/${id}`,
  groups:            '/groups',
  group:             (id: string) => `/groups/${id}`,
  groupCourse:       (id: string) => `/groups/${id}/course`,
  orders:            '/orders',
  orderCancel:       (id: string) => `/orders/${id}/cancel`,
  settings:          '/settings',
  courses:           '/courses',
  course:            (id: number) => `/courses/${id}`,
  drinkPlans:        '/drink-plans',
  drinkPlan:         (id: number) => `/drink-plans/${id}`,
  staff:             '/staff',
  staffMember:       (id: string) => `/staff/${id}`,
  staffSessions:     (staffId: string) => `/staff/${staffId}/sessions`,
  staffSession:      (staffId: string, sessionId: string) => `/staff/${staffId}/sessions/${sessionId}`,
  seatTables:        '/seat-tables',
  seatTable:         (id: number) => `/seat-tables/${id}`,
  seatLayout:        '/seat-layout',
  customerGroup:       (id: string) => `/customer/groups/${id}`,
  customerMenus:       (id: string) => `/customer/groups/${id}/menus`,
  customerGroupOrders: (id: string) => `/customer/groups/${id}/orders`,
  customerOrders:      '/customer/orders',
  customerBill:        (id: string) => `/customer/groups/${id}/bill`,
  customerCallStaff:   (id: string) => `/customer/groups/${id}/call-staff`,
  customerSettings:    '/customer/settings',
  platformAuthLogin:  '/platform/auth/login',
  platformAuthLogout: '/platform/auth/logout',
  platformAuthMe:     '/platform/auth/me',
  platformStores:     '/platform/stores',
  platformStore:      (id: number) => `/platform/stores/${id}`,
} as const
