export const EP = {
  authMe:            '/auth/me',
  authLogin:         '/auth/login',
  authLogout:        '/auth/logout',
  sessionsCurrent:   '/sessions/current',
  sessions:          '/sessions',
  session:           (id: number) => `/sessions/${id}`,
  sessionReport:     (id: number) => `/sessions/${id}/report`,
  menus:             '/menus',
  menu:              (id: number) => `/menus/${id}`,
  categories:        '/categories',
  category:          (id: number) => `/categories/${id}`,
  subcategories:     '/subcategories',
  subcategory:       (id: number) => `/subcategories/${id}`,
  seats:             '/seats',
  seat:              (id: number) => `/seats/${id}`,
  groups:            '/groups',
  group:             (id: string) => `/groups/${id}`,
  orders:            '/orders',
  orderCancel:       (id: string) => `/orders/${id}/cancel`,
  settings:          '/settings',
  courses:           '/courses',
  drinkPlans:        '/drink-plans',
  staff:             '/staff',
  staffMember:       (id: string) => `/staff/${id}`,
  seatTables:        '/seat-tables',
  seatTable:         (id: number) => `/seat-tables/${id}`,
  seatLayout:        '/seat-layout',
} as const
